project:
  type: website
  output-dir: docs

website:
  title: "OpenInfra Korea User Group"
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/openstack-kr/openstack-book
      - icon: facebook
        href: https://www.facebook.com/groups/openstack-kr
      - icon: discord
        href: https://discord.gg/3ZzKMJKtPg
      - icon: chat-square-text
        href: https://forum.openinfra-kr.org/
  sidebar:
    style: docked
    search: true
    contents:
      - text: "목록"
        contents:
        - text: "목차"
          file: lectures/index.qmd
        - text: "1장. 오픈스택 개요"
          file: lectures/ch1_lec.qmd
        - text: "2장. 오픈스택 설치 가이드"
          file: lectures/ch2_lec.qmd

format:
  html:
    theme:
      - flatly
      - custom.scss
    toc: true
    lang: ko
    include-after-body: _footer.html